/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupo1.trasversal.vistas;

/**
 *
 * @author brand
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmInscripcion = new javax.swing.JMenu();
        jmiAlumno = new javax.swing.JMenuItem();
        jmiMateria = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmiModificarAlumno = new javax.swing.JMenuItem();
        jmiBajaAlumno = new javax.swing.JMenuItem();
        jmiConsultarAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiModificarMateria = new javax.swing.JMenuItem();
        jmiBajaMateria = new javax.swing.JMenuItem();
        jmiConsultarMateria = new javax.swing.JMenuItem();
        jmInforme = new javax.swing.JMenu();
        jmiInformeAlumno = new javax.swing.JMenuItem();
        jmiInformeMateria = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuBar1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jMenuBar1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jmInscripcion.setText("Inscripcion");

        jmiAlumno.setText("Alumno");
        jmiAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlumnoActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmiAlumno);

        jmiMateria.setText("Materia");
        jmiMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMateriaActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmiMateria);

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmiSalir);

        jMenuBar1.add(jmInscripcion);

        jmAlumno.setText("Alumno ");

        jmiModificarAlumno.setText("Modificar Alumno");
        jmAlumno.add(jmiModificarAlumno);

        jmiBajaAlumno.setText("Baja Alumno");
        jmAlumno.add(jmiBajaAlumno);

        jmiConsultarAlumno.setText("Consultar Alumno");
        jmAlumno.add(jmiConsultarAlumno);

        jMenuBar1.add(jmAlumno);

        jmMateria.setText("Materia");

        jmiModificarMateria.setText("Modificar Materia");
        jmiModificarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmiModificarMateria);

        jmiBajaMateria.setText("Baja Materia");
        jmMateria.add(jmiBajaMateria);

        jmiConsultarMateria.setText("Consultar Materia");
        jmMateria.add(jmiConsultarMateria);

        jMenuBar1.add(jmMateria);

        jmInforme.setText("Informes");

        jmiInformeAlumno.setText("Alumnos");
        jmInforme.add(jmiInformeAlumno);

        jmiInformeMateria.setText("Materias");
        jmInforme.add(jmiInformeMateria);

        jMenuBar1.add(jmInforme);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiModificarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiModificarMateriaActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
    dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlumnoActionPerformed
         jDesktopPane1.removeAll();
        InscripcionAlumno ia = new InscripcionAlumno();
        ia.setVisible(true);
        jDesktopPane1.add(ia);
        jDesktopPane1.moveToFront(ia);
        jDesktopPane1.repaint();


        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAlumnoActionPerformed

    private void jMenuBar1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jMenuBar1CaretPositionChanged
        
    }//GEN-LAST:event_jMenuBar1CaretPositionChanged

    private void jmiMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriaActionPerformed

         jDesktopPane1.removeAll();
        InscripcionMateria im = new InscripcionMateria();
        im.setVisible(true);
        jDesktopPane1.add(im);
        jDesktopPane1.moveToFront(im);
        jDesktopPane1.repaint();


        // TODO add your handling code here:
    }//GEN-LAST:event_jmiMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmInforme;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenuItem jmiAlumno;
    private javax.swing.JMenuItem jmiBajaAlumno;
    private javax.swing.JMenuItem jmiBajaMateria;
    private javax.swing.JMenuItem jmiConsultarAlumno;
    private javax.swing.JMenuItem jmiConsultarMateria;
    private javax.swing.JMenuItem jmiInformeAlumno;
    private javax.swing.JMenuItem jmiInformeMateria;
    private javax.swing.JMenuItem jmiMateria;
    private javax.swing.JMenuItem jmiModificarAlumno;
    private javax.swing.JMenuItem jmiModificarMateria;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
